name: CI

on:
  push:
    branches: [main, master, develop, develop_keypoint_orientation_sfm]
  pull_request:
    branches: [main, master, develop, develop_keypoint_orientation_sfm]

 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-tests:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,  macOS-latest, windows-latest]
    env:
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - uses: actions/checkout@v2

      - name: Git submodule
        run: |
          mkdir ./build
          git submodule update -i

      - name: Configure CMake
        working-directory: ./build
        run: |
          cmake ../src \
          -DOpenMVG_BUILD_TESTS=ON \
          -DOpenMVG_BUILD_EXAMPLES=ON \
          -DOpenMVG_BUILD_SOFTWARES=ON \
          -DSCHUR_SPECIALIZATIONS=OFF \
          -DTARGET_ARCHITECTURE=core
        shell: bash

      - name: Build
        working-directory: ./build
        run: |
           if [ "$RUNNER_OS" == "Windows" ]; then
              cmake --build . --config Release
           else
              cmake --build . -- -j$(nproc)
           fi
        shell: bash


      - name: Unit Tests
        working-directory: ./build
        run: |
          ctest -j$(nproc) --build-config Release
